version: '3.8'

services:
  nodejs-metrics:
    container_name: nodejs-metrics
    build:
      context: "./nodejs-metrics"
      dockerfile: Dockerfile
    #command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./nodejs-metrics:/usr/src/app 

  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - nodejs-metrics