global:
  scrape_interval: "15s"
  scrape_timeout: "5s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: nodejs_metrics
    static_configs:
      - targets: ['nodejs-metrics:3000']
        labels:
          app: nodejs_metrics
