global:
  scrape_interval: "15s"
  scrape_timeout: "5s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: api
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ['api:80']
        labels:
          versao: "1.0"
  
  - job_name: mongodb_exporter
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ['mongoexporter:9216']
        labels:
          database: mongodb
